### ISSUE TITLE
Game crashes when hovering over certain items

### ISSUE THREAD

**Issue by Linkling64** [LunaPixelStudios/SteamPunk#309] opened 2024-08-15 02:10 UTC
### Describe the Bug

When hovering over certain items in the JEI recipes GUI, the game crashes. I think it's all items from a certain mod, but I can't see what mod it is because when I hover over it, it crashes before I can see the mod. It gives the error "java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 2". One item it does this for is the item that appears in the bottom left of the GUI when looking at the recipe for an eternal stella. (I don't know what the item is because, again, it crashes before it shows up.) This happens every time

### Reproduction Steps

1. Search "eternal stella" in the JEI menu and click it to see the recipe
2. Hover over the item in the bottom left of the screen (Don't know what it is, it is black and yellow and looks like a pedestal or something)
3. The game should crash
*This is just one example, there are other items that this happens with too. I think they're all from the same mod

### Screenshots and Videos

Here is a video of the bug in action (sry for the low quality)
https://github.com/user-attachments/assets/fdbe9202-050d-4a19-a953-bdcc7601e618

### Crash Report or Log

https://gist.github.com/Linkling64/5c878454deaa1353a1e15987778ee878

### Operating System

Sonoma 14.6.1

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v24

**Comment by batteryhun78** [comment] 2024-08-17 18:07
I was just reading about the modpack's bugs, weeks ago my friend had this problem (hovering over item, causes crash, but not for me.) 

Found it was caused by the coldsweat mod, we updated it to the latest one "ColdSweat-2.3-b04f" and it worked. 

The modpack currently has "ColdSweat-2.3-b03d"
We updated to "ColdSweat-2.3-b04f"

The crash is caused by ColdSweat-2.3-b03e, where:
"Fixes:
* Fixed another crash related to item tooltips"

I hope the pack is going to be updated soon, mods are out of date :/

**Comment by batteryhun78** [comment] 2024-08-19 18:13
Might be a related fix 
https://github.com/mezz/JustEnoughItems/commit/03c9f113523d255953517c779ef62de359b02255

**Comment by qwek1** [comment] 2024-08-27 10:04
fixed on v25

**Closed by qwek1** 2024-08-27 10:04 UTC
Labels: bug, Forge, 1.15
