### ISSUE TITLE
Pixel Armor Broken

### ISSUE THREAD

**Issue by BionicShadow** [LunaPixelStudios/SteamPunk#346] opened 2024-12-09 02:58 UTC
### Describe the Bug

I built the Pixel armor and when i put a full set of brass plates in all slots all armors in the game have a forever increasing armor value. If i remove the pixel armor or remove all the brass plates the value stops increasing but doesn't return to normal. If i put 1 brass plate back into a slot the value starts increasing again. It's doesn't get fixed if i restart the game either.

### Reproduction Steps

1.Made Pixel armor
2.Added Brass Plates to All slots
3.See armor value increasing non-stop
...

### Screenshots and Videos

![2024-12-08_21 09 34](https://github.com/user-attachments/assets/876abb01-0bf2-4cc6-af59-20df387a2637)

![2024-12-08_21 09 39](https://github.com/user-attachments/assets/c539e0f6-10f5-4c1a-ae72-103c60983d35)

![2024-12-08_21 09 41](https://github.com/user-attachments/assets/dc766664-9f75-402b-b376-7f8407154847)

![2024-12-08_21 09 43](https://github.com/user-attachments/assets/a643deaf-9086-4af6-b508-872b89483e57)

![2024-12-08_21 45 14](https://github.com/user-attachments/assets/d72f645c-d981-463c-a83c-44c3762a4937)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v10

### Other Mods

I added Ftb Ultimine to the mod pack

**Comment by stubkan** [comment] 2024-12-16 01:41
Confirmed.  Playing on Steampunk LPS public mmc server with 10.hf , adding brass plates breaks it.

![2024-12-16_01 37 32](https://github.com/user-attachments/assets/40d415d5-de79-4e6e-919a-d60c7ee696fa)

**Comment by stubkan** [comment] 2024-12-16 02:08
EDIT: It seems it breaks far more - and has rendered my character itself broken 

Removed ALL armour, items and disabled all skills, etc and my character still has maxed armour.  All other armour also exhibit inflated armour stat

This is a pretty serious bug

![image](https://github.com/user-attachments/assets/d6c63c22-b4b2-4f0a-962b-8d23570ce7eb)

![image](https://github.com/user-attachments/assets/fb9862c9-2688-486e-a818-77fce799b09e)

observe maxed armour here on hotbar while wearing nothing

![image](https://github.com/user-attachments/assets/30206ab0-27ae-446e-ad9a-797aa4ab4710)

**Comment by qwek1** [comment] 2024-12-26 13:09
Its an compatibility issue between scorched guns and protection pixel, so it should be reported to them instead. This might've been fixed in v11 though.

**Closed by qwek1** 2024-12-26 13:09 UTC
Labels: bug, Forge

**Comment by stubkan** [comment] 2024-12-26 14:52
@qwek1 

Closing it because it "might" be fixed?  

Why would you not wait for confirmation it is actually fixed, or try it out yourself - before marking it as fixed?

Its still not fixed.  Its pretty easy to test - just add armour plates to any pixel armour and you'll see.

**Comment by BionicShadow** [comment] 2024-12-26 17:25
Wow wait 3 weeks hoping for a fix just to be told might be fixed. Its your mod pack that your using both in, so it is your issue if there not working correctly. Your just being absolutely lazy and unhelpful.

**Comment by qwek1** [comment] 2024-12-28 21:46
> @qwek1
> 
> Closing it because it "might" be fixed?
> 
> Why would you not wait for confirmation it is actually fixed, or try it out yourself - before marking it as fixed?
> 
> Its still not fixed. Its pretty easy to test - just add armour plates to any pixel armour and you'll see.

The issue was closed because its an issue with the mod and not the modpack, there is nothing I can do on my end to fix the issue.

**Comment by stubkan** [comment] 2024-12-29 14:05
@qwek1

Bionic has a point - it is kind of the modpack creators responsibility to make sure their modpack actually is in a working state with their chosen mods.

> there is nothing I can do on my end to fix the issue.
Thats not really true, there are two things you COULD do:

1. Update Steampunk to include the latest PP version which has a bunch of fixes, which MAY fix it

2. Downgrade PP or Scorched to a version where both work together properly
