### ISSUE TITLE
aurum chest still has texture bug

### ISSUE THREAD

**Issue by Gost-GitL** [LunaPixelStudios/SteamPunk#268] opened 2024-05-29 03:41 UTC
### Describe the Bug

as title

### Reproduction Steps

1.search it in jei
2.chest with proper texture do not has recipe
3.can only obtain the bug chest as vanilla
...

### Operating System

win10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

23.5

### Optifine

No

**Comment by qwek1** [comment] 2024-05-29 12:15
could you send a screenshot?

**Comment by Gost-GitL** [comment] 2024-05-30 10:07
> could you send a screenshot?

![Uploading IMG_20240530_180725_1.jpg…]()

**Comment by qwek1** [comment] 2024-05-31 09:42
I cant view the image

**Comment by stellarisnp** [comment] 2024-06-02 16:20
> I cant view the image

it exists in the original thread, which is marked as closed.
https://github.com/LunaPixelStudios/SteamPunk/issues/245

**Comment by Gost-GitL** [comment] 2024-06-06 03:49
> I cant view the image



> > I cant view the image
> 
> it exists in the original thread, which is marked as closed. #245

sure, the image there could represent how the bug is, because it still exists in the latest version

**Comment by Gost-GitL** [comment] 2024-06-06 04:25
also, it would be better to have a solution without updating modpack

**Comment by chorbintime** [comment] 2024-06-08 23:25
update the modpack - theres no way around updating. theres no reason not to, your world is completely safe, and if you stay on an old version you will experience issues.

**Comment by Gost-GitL** [comment] 2024-06-09 05:57
> update the modpack - theres no way around updating. theres no reason not to, your world is completely safe, and if you stay on an old version you will experience issues.

I mean, I've already updated to the latest version 23.5, but the texture bug still exists. So could you fix it in next update?

**Comment by Gost-GitL** [comment] 2024-06-09 06:30
The modpack is sufficiently polished, but something can be further refined.
1, let modded plants and leaves be compatible with the waving texture from complementary shader
2, copper backpack does not have straps, and when it comes to gameplay, it is op for its inventory capacity in contrast to gold backpack.
3, moving create contraption sometimes becomes black in some part.
4, magnet 🧲 on/off button is hidden by faithless UI

**Comment by Gost-GitL** [comment] 2024-06-10 05:45
Also, after getting processed by Chipped mod workbench, modded timbers from Every Compat don't have fusion (connected) texture except the aurum, which is weird.

**Comment by qwek1** [comment] 2024-06-27 22:54
There are 2 versions of the Aurum Chest, both from Every Compat. One with proper textures and no recipe, and the other one with the vanilla chest texture with the correct recipe. 

It might be an issue with Every Compat, will look into the issue soon!

![icqerqmage](https://github.com/LunaPixelStudios/SteamPunk/assets/133406949/ec9e372e-0e70-4ca9-bfb8-5c6dc8cf7f60)

**Comment by SHXRKIEgg** [comment] 2024-07-05 08:01
This is most likely caused by every compat mod, we cant really fix it and you could remove the mod to fix it but we cant do that atm as it can cause a lot of issues for the users who have the chests

**Closed** 2024-07-12 03:07 UTC
Labels: bug, Forge
