### ISSUE TITLE
Death respawn bug

### ISSUE THREAD

**Issue by DefNotTas2** [LunaPixelStudios/SteamPunk#104] opened 2024-01-18 23:02 UTC
### Describe the Bug

When dying in steampunk, it would let me respawn and then I immediately die once again and have to click the respawn button again. This glitches out my character and puts it in a constant dying animation. I can still move around just fine and my character is still two blocks tall.

### Reproduction Steps

1. Die 
2. Clicks respawn button
3. Dies again immediately
4. character glitches out
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/132390972/a97b9a6e-4067-4f08-b32c-c8fded255f90)

### Operating System

Window 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Steampunk [LPS] v21

### Optifine

No

### Other Mods

None

**Comment by SHXRKIEgg** [comment] 2024-01-18 23:22
This is an ongoing issue that I cant reproduce myself to fix, just restart the game and it should be fixed.

**Closed by SHXRKIEgg** 2024-01-18 23:22 UTC
Labels: bug, Forge
