### ISSUE TITLE
Scopes zoom in too much/don't show up

### ISSUE THREAD

**Issue by total-snarf** [LunaPixelStudios/SteamPunk#261] opened 2024-05-24 22:04 UTC
### Describe the Bug

Both medium and long scopes don't show up in first person. This applies to any gun I put them on. There is a zoom affect applied, but it seems to be too much, and puts my vision in front of the scope. I'm not using shaders and have not changed/added to the modpack.

### Reproduction Steps

1.get gun
2.put scope on gun
3.hold right mouse button
...

### Screenshots and Videos

![2024-05-24_22 54 57](https://github.com/LunaPixelStudios/SteamPunk/assets/119135318/c8dee48a-5477-4928-a3ed-66ff9ecfc2c6)
![2024-05-24_22 54 59](https://github.com/LunaPixelStudios/SteamPunk/assets/119135318/3f4b7f5c-30e2-4b96-93fe-2752bc5e4d7a)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v23.5

### Optifine

No

**Comment by qwek1** [comment] 2024-05-31 09:42
try updating the Create Guns resourcepack

**Comment by total-snarf** [comment] 2024-05-31 11:24
> try updating the Create Guns resourcepack

What do you mean by updating? 

I have used this pack through 4 separate installs over 3 different minecraft launchers, and this issue is consistent. I've seen others play this pack (on youtube) and using these scopes without issue, so I don't know what's going wrong for me to break them.

**Comment by chorbintime** [comment] 2024-05-31 12:44
Download the latest version of the resourcepack from its Curseforge page, replacing the old one

**Comment by total-snarf** [comment] 2024-06-01 02:52
> Download the latest version of the resourcepack from its Curseforge page, replacing the old one

Thankyou, this has fixed the problem. It seems the modpack includes an outdated version of the resource pack

**Comment by TheFafalStudios** [comment] 2024-06-01 17:34
Hi,
I've encountered this exact issue but I have found the actual root cause.
This resource pack:  https://www.curseforge.com/minecraft/texture-packs/create-guns-a-scorched-addon
It overwrites the create guns resource pack scopes into a broken version.

**Comment by total-snarf** [comment] 2024-06-01 17:40
If you remove the Scorched Guns resource pack, the original Create Guns textures work fine.
If you remove the Create Guns Resource pack, the new Scorched Guns scopes work perfectly.

It seems like there's currently some compatibility issues between the two.

**Comment by TheFafalStudios** [comment] 2024-06-01 17:48
you can also kind of patch it by deleting medium_scope.json and long_scope.json from the pack, then you  get the other long scopes that work

**Comment by qwek1** [comment] 2024-06-05 22:44
will be fixed in the next update

**Closed** 2024-06-10 23:05 UTC
Labels: bug, Forge
